#:schema node_modules/wrangler/config-schema.json
name = 'vibesmp-cdn'
main = "src/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]


[observability]
enabled = true

[[r2_buckets]]
binding = "STUFF_BUCKET" 
bucket_name = "cdn"
preview_bucket_name = "cdn"

[[routes]]
pattern = "cdn.vibesmp.net"
custom_domain = true

[[kv_namespaces]]
binding = "AUTH_STORE"
id = "019b1f7348da4a2eaa7a28aed4a2f38a"
preview_id = "019b1f7348da4a2eaa7a28aed4a2f38a"