#:schema node_modules/wrangler/config-schema.json
name = "stuff-cdn"
main = "src/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]


[observability]
enabled = true

[[r2_buckets]]
binding = "STUFF_BUCKET" 
bucket_name = "stuff"
preview_bucket_name = "stuff"

[[routes]]
pattern = "cdn.soestin.nl"
custom_domain = true

